#!/bin/bash

# Define colors using tput
GREEN=$(tput setaf 2)
RESET=$(tput sgr0)

echo -e "${GREEN}Step 1: Updating|Upgrading packages\n=====================================${RESET}"
sudo apt-get update -y && sudo apt-get upgrade -y

echo

echo -e "${GREEN}Step 3: Repair broken packages/dependencies\n=============================================${RESET}"
sudo apt --fix-missing update -y
sudo apt-get update -y
sudo apt-get install -f -y

echo

echo -e "${GREEN}Step 4: Removing all the junk files\n=====================================${RESET}"
sudo apt-get clean -y
sudo apt-get autoclean -y
sudo apt-get autoremove -y

echo

echo -e "${GREEN}Last step: Updating packages\n==============================${RESET}"
sudo apt-get update -y && sudo apt-get upgrade -y

echo

echo -e "${GREEN}\tCONGRATULATIONS $USER!!\n \tYour system is clean and up-to-date${RESET}"

echo
